package cn.qtech.bigdata.model;

import java.util.List;

import static java.util.Arrays.asList;


public class AA {
    public static  final List<String> AAStringValue = asList(
            "LensRejectedTotal",
            "MTBA",
            "EW3_Dispense_Count",
            "PauseReason",
            "AA4_Tilt_Delay",
            "GrossUPH",
            "AA4_VCM_Z_Offset",
            "AA2CycleTime",
            "AA4_XY_Delay",
            "EW1_Dispense_Pressure",
            "CardIDReadTime",
            "dtu_program_version",
            "EW2_Glue_ID",
            "device_type",
            "AA2_VCM_Z_Offset",
            "AA2_Z_Delay",
            "client_id",
            "MTBF",
            "AA1_XY_Delay",
            "create_date_number",
            "dev_template_unique_id",
            "iot_unique_message_id",
            "AA1_Tilt_Delay",
            "LotName",
            "id",
            "create_date",
            "AA4BondPosOffsetT",
            "EW4_Glue_ID",
            "AlarmCount",
            "Status",
            "EW1_Dispense_Time_Limit",
            "device_id",
            "SelectModuleStation4",
            "AA2_UV_Time",
            "SelectModuleStation3",
            "SelectModuleStation2",
            "SelectModuleStation1",
            "CardID",
            "EW1_Dispense_Height",
            "EW3_Dispense_Pressure",
            "EW4_Dispense_Height",
            "MAC",
            "NetUPH",
            "CncStatus",
            "AA3CycleTime",
            "EW4_Dispense_Count",
            "EW2_Dispense_Pressure",
            "TotalProductiveTime",
            "UnitRejectTotal",
            "AA4_Z_Delay",
            "AlarmID",
            "EW1_Dispense_Speed",
            "EW3_Dispense_Count_Limit",
            "EW2_Dispense_Height",
            "EW4_Dispense_Pressure",
            "AA1BondPosOffsetT",
            "transformed_date",
            "AA1_VCM_Z_Offset",
            "AA1_Z_Delay",
            "AA3_VCM_Z_Offset",
            "EW1_Glue_ID",
            "EW2_Dispense_Time_Limit",
            "EW3_Glue_ID",
            "AA2_XY_Delay",
            "EW2_Dispense_Count_Limit",
            "EW3_Dispense_Time_Limit",
            "EW2_Dispense_Count",
            "data_col_time",
            "EW4_Dispense_Speed",
            "AA1CycleTime",
            "AA2BondPosOffsetT",
            "AA2_Tilt_Delay",
            "AA3_UV_Time",
            "AA4_UV_Time",
            "AverageCycleTime",
            "AA4CycleTime",
            "EW1_Dispense_Count",
            "EW3_Dispense_Speed",
            "AA1_UV_Time",
            "UnitBondTotal",
            "EW4_Dispense_Count_Limit",
            "AA3_Tilt_Delay",
            "EW1_Dispense_Count_Limit",
            "receive_date",
            "AA3_Z_Delay",
            "EW3_Dispense_Height",
            "TotalIdleTime",
            "EW2_Dispense_Speed",
            "EW4_Dispense_Time_Limit",
            "AA3BondPosOffsetT",
            "AA3_XY_Delay"
    );

}