package cn.qtech.bigdata.model;


import java.util.List;

import static java.util.Arrays.asList;

public class WBXtreme {

    public static  final List<String> WBStringValue = asList(
            "iot_unique_message_id",
            "LotName",
            "id",
            "MAC",
            "transformed_date",
            "receive_date",
            "device_type",
            "deviceName",
            "client_id",
            "dev_template_unique_id",
            "create_date",
            "dtu_program_version",
            "data_col_time",
            "Capillary_count_warning_limit",
            "Contact_Search_Threshold_1",
            "Contact_Search_Threshold_2",
            "SPOOL_FULL_TIME_11",
            "SPOOL_START_TIME_12",
            //
            "Unscheduled_Down_Time",
            "Standby_Time",
            "Capillary_count",
            "UPH_Net",
            "NonScheduled_Down_Time",
            "Wire_Size_EFO_Parameter",
            "UPH_Ideal",
            "Number_of_Wire_clamp_errors",
            "Number_of_Etorch_errors",
            "Number_of_wire_bonded",
            "Spool_Length_Wire_Usage",
            "Capillary_count_stop_limit",
            "Wire_turn_count",
            //
            "MTBA",
            "EFO_FAB_Block",
            "Number_of_2nd__non_stick_error",
            "BSOB_Wire_1st_Contact_Power",
            "MTBF",
            "EFO_Current_FAB_BLK_0",
            "Number_of_window_clamp_error",
            "EFO_Current_FAB_BLK_1",
            "Total_Idle_Time",
            "Number_of_lead_tolerance_fail",
            "BSOB_Ball_1st_Bond_Power",
            "Number_of_lead_quality_fail",
            "Status",
            "PreHeater_Value",
            "Heater_Value",
            "Bond_Scrub_Force_1",
            "BSOB_Ball_1st_Contact_Power",
            "BSOB_Wire_1st_Contact_Time",
            "Number_of_die_skipped",
            "Bond_Scrub_Amplitude_1",
            "Bond_Scrub_Amplitude_2",
            "BSOB_Wire_2nd_Contact_Force",
            "AlarmID",
            "Number_of_output_magazine_fail",
            "Number_of_ejector_error",
            "DownTime",
            "Post_Bond_Heater_Value",
            "Number_of_index",
            "BSOB_Wire_2nd_Bond_Force",
            "BSOB_Wire_1st_Bond_Time",
            "FAB_size_EFO_Parameter",
            "UnitBondTotal",
            "Failures",
            "UpTime",
            "Number_of_Assists",
            "Number_of_die_quality_fail",
            "BSOB_Ball_2nd_Contact_Power",
            "Number_of_Short_of_Tail",
            "Standby_Power1_936",
            "BSOB_Ball_2nd_Bond_Force",
            "Number_of_1st__non_stick_error",
            "BSOB_Wire_2nd_Contact_Power",
            "Processed_Quantity",
            "BSOB_Wire_1st_Contact_Force",
            "Production",
            "BSOB_Ball_1st_Bond_Time",
            "Number_of_local_lead_fail",
            "BSOB_Ball_2nd_Bond_Time",
            "Fire_Level_Factor",
            "Standby_Power1",
            "Number_of_die_tolerance_fail",
            "Bond_Scrub_Power_1",
            "CncStatus",
            "Number_of_ball_missing",
            "BSOB_Wire_2nd_Bond_Power",
            "BSOB_Ctrl_Standby_Power2",
            "BSOB_Wire_1st_Bond_Force",
            "BSOB_Ctrl_Standby_Power1",
            "BSOB_Wire_2nd_Bond_Time",
            "BSOB_Ball_1st_Contact_Time",
            "BSOB_Ball_1st_Contact_Force",
            "BSOB_Ball_2nd_Contact_Force",
            "BSOB_Wire_2nd_Contact_Time",
            "BSOB_Wire_1st_Bond_Power",
            "BSOB_Ball_2nd_Bond_Power",
            "BSOB_Ball_2nd_Contact_Time",
            "BSOB_Ball_1st_Bond_Force",
            "Standby_Power2_937",
            //
            "create_date_number",
            "device_id"
    );

}
